version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11.5"
  jobs:
    pre_build:
      - pip install --upgrade pip

sphinx:
  configuration: ML_PT_Pyworkflow/docs/source/conf.py

python:
  install:
    - requirements: ML_PT_Pyworkflow/requirements.txt
